version: '3.8'

services:
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_DATABASE: nest
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql-data:/var/lib/mysql